Student_Performance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
   path('',include('performance.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

performance/urls.py
from django.urls import path

from .views import FileCreateView,FileDetailView,FileDeleteView,FileListView, LoginView,DashboardView, signout , SearchView, Home





app_name = 'performance'
urlpatterns = [

    path('', Home.as_view(), name='home-view'),
    path('login/', LoginView.as_view(), name='login-view'),
    path('dashboard/', DashboardView.as_view(), name='dashboard-view'),

    path('logout/',signout,name='logout'),


    path('file-create/',FileCreateView.as_view(),name='file-create'),
    path('file-list/',FileListView.as_view(),name='file-list'),
    path('file-detail/<int:pk>/',FileDetailView.as_view(),name='file-detail'),
    #path('detail/file-update/<int:pk>/',FileUpdate.as_view(),name='file-update'),
    path('file-delete/<int:pk>/',FileDeleteView.as_view(),name='file-delete'),

    path('search/<int:pk>',SearchView.as_view(),name='file-search'),

]

templates/partials/_footer.html
<div class="row pt-5 mt-5 text-center">
            <div class="col-md-12"  style="background-color: ##fee2b3 !important;">
              <div class="border-top pt-5">
                <p>
               Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
               Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
              </p>
              </div>
            </div>
</div>


<style>
    .col-md-12{

        background-color: ##fee2b3 !important;
    }
</style>

templates/partials/_home.html
        <div class="breadcome-area" style="margin-top:50px;">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Dashboard</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

templates/partials/_login-form.html
{% load static %}


<html>
<head>

     <link rel="stylesheet" href="{% static 'css/login.css' %}">
<!--    <link rel="stylesheet" type="text/css" href="style.css">-->
</head>
    <body>
    <div class="hero overlay" style="background-image: url('{% static "home/images/hero_bg_1.jpg" %}');">




        <div class="error-pagewrap">
		<div class="error-page-int" style="opacity:1;">
			<div class="text-center m-b-md custom-login" >
				<h3 style="color:white;">PLEASE LOGIN </h3>

			</div>
			<div class="content-error">
				<div class="hpanel">
                    <div class="panel-body">
                        <form id="loginForm" action="{% url 'performance:login-view' %}" class="add-department" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="Email">Email</label>
                                {{form.email}}
                                {{form.errors.email}}
                                <span class="help-block small">Your email should like example@gmail.com</span>
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                {{form.password}}
                                {{form.errors.password}}
                                <span class="help-block small"> Your strong password </span>
                            </div>
                            <button class="btn btn-success btn-block loginbtn">Login</button>

                        </form>
                    </div>
                </div>
			</div>
		</div>
    </div>


                        {% if messages %}
                            {% for message in messages %}
                                {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

                            {% endfor %}

                        {% endif %}




    </div>




    </body>
</html>

templates/partials/_mobilemenu.html
<!-- Mobile Menu start -->
            <div class="mobile-menu-area">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="mobile-menu">
                                <nav id="dropdown">
                                    <ul class="mobile-menu-nav">
                                        <li>
                                            <a  href="{% url 'performance:dashboard-view' %}" aria-expanded="false"><span class="educate-icon educate-home icon-wrap"></span> <span class="mini-click-non">DASHBOARD</span></a>
                                        </li>



                                         <li>
                            <a  href="{%url 'performance:file-list' %}" aria-expanded="false"><span class="fa fa-product-hunt"></span> <span class="mini-click-non">FILES</span></a>

                        </li>
                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false"><span class="educate-icon educate-checked edu-checked-pro admin-check-pro"></span> <span class="mini-click-non">SUPPORT</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="Projects List" href="{% url 'performance:file-create' %}"><span class="mini-sub-pro">UPLOAD FILES</span></a></li>
                                <li><a title="Projects List" href="{% url 'performance:file-list' %}"><span class="mini-sub-pro">LIST OF FILES</span></a></li>



                            </ul>
                        </li>








                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Mobile Menu end -->

templates/partials/_navbar.html
{% load static %}
<div class="all-content-wrapper">
    <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="logo-pro" style="margin-top: 40px;" >
                    </div>
                </div>
            </div>
        </div>
    <div class="header-advance-area">
        <div class="header-top-area" style="background:#fee2b3; height:13%;" >
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="header-top-wraper">
                                <div class="row">
                                    <div class="col-lg-1 col-md-0 col-sm-1 col-xs-12">

                                    </div>
                                    <div class="col-lg-6 col-md-7 col-sm-6 col-xs-12">
                                    </div>
                                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                        <div class="header-right-info">
                                            <ul class="nav navbar-nav mai-top-nav header-right-menu">
                                                        <li class="nav-item">


                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class="active"><a href="{% url 'performance:home-view' %}" class="nav-link" style="color:black;">Home</a></li>







<!--                     <li class="nav-item dropdown nav-user" style="color:#00FF00;">-->

                <a href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false" class="fas fa-user-circle fa-2x "style="margin-top:10px;color:#00FF00;"></a>
                <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                    <div class="nav-user-info">
                        <h5 class="mb-0 text-white nav-user-name" style="color:#00FF00">{{request.user}}</h5>
                        <span class="status"></span><span class="ml-2">Available</span>
                    </div>

                    <a class="dropdown-item" href="" style="color:#c33;"><i class="fas fa-power-off mr-2" style="color:#c33;"></i>Logout</a>
                </div>
            </li>





<!--                                                            <a href="#" data-toggle="" role="button" aria-expanded="false" class="nav-link">-->
<!--                                                                    <span class="admin-name">Welcome {{request.user}}</span>-->

<!--                                                                </a>-->
<!--                                                             <a href="{% url 'performance:logout' %}" data-toggle="" role="button" aria-expanded="false" class="nav-link">-->
<!--                                                                    <span class="admin-name">Logout</span>-->

<!--                                                                </a>-->

                                                        </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>







<style>

ul {
    list-style: outside none none;
}
.text-right {
    text-align: right !important;
}
.text-right {
    text-align: right;
}
.text-lg-left {
    text-align: left !important;
}
body {
    line-height: 1.7;
    color: #364d59 !important;
    font-weight: 300;
    font-size: 1rem;

}


.nav-link {
    margin-right: 20px;
    margin-left: 20px;
}


 </style>

templates/partials/_register-form.html
{% load static %}
<div class="error-pagewrap">
		<div class="error-page-int">
			<div class="text-center custom-login">
				<h3>Registration</h3>

			</div>
			<div class="content-error">
				<div class="hpanel">
                    <div class="panel-body">
                        <form id="loginForm" class="add-department" action="{% url 'performance:register-view' %}"  method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="form-group col-lg-12">
                                    <label for="Username">Username</label>
                                    {{form.username}}
                                </div>
                                <div class="form-group col-lg-12">
                                    <label for="Email">Email</label>
                                    {{form.email}}
                                    <span class="help-block small">Your email should like example@gmail.com</span>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="first_name">First Name</label>
                                    {{form.first_name}}
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="last_name">Last Name</label>
                                    {{form.last_name}}
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="Password">Password</label>
                                    {{form.password}}
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="confirm_password">Repeat Password</label>
                                    {{form.confirm_password}}
                                </div>

                            </div>
                            <div class="text-center">
                                <button class="btn btn-success loginbtn">Register</button>
                                <button class="btn btn-default">Cancel</button>
                            </div>
                        </form>
                    </div>
                </div>
			</div>

		</div>
    </div>

templates/partials/_sidebar.html
{% load static%}
<style>
    .this-is-main-logo{
    width:100px;
    height:56px;
    }
</style>
<style>
    # sidebar-view{
    background:#f96359;
    }
</style>
<!-- Start Left menu area -->
    <div class="left-sidebar-pro" style="margin-top:150px; position:fixed;">
        <nav id="sidebar" class="" style="background-color:#00ff99;">

            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1"  style="background-color:#00ff99; color:white;">
                        <li>
                            <a  href="{% url 'performance:dashboard-view' %}" aria-expanded="false"><span class="educate-icon educate-home icon-wrap"></span> <span class="mini-click-non">DASHBOARD</span></a>
                        </li>


                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false"><span class="educate-icon educate-checked edu-checked-pro admin-check-pro"></span> <span class="mini-click-non">FILES</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="Projects List" href="{% url 'performance:file-create' %}"><span class="mini-sub-pro">UPLOAD FILES</span></a></li>
                                <li><a title="Projects List" href="{% url 'performance:file-list' %}"><span class="mini-sub-pro">LIST OF FILES</span></a></li>
                                <li><a title="Projects List" href="{% url 'performance:file-search' %}"><span class="mini-sub-pro">SEARCH RESULT</span></a></li>



                            </ul>
                        </li>



                    </ul>
                </nav>
            </div>
        </nav>
    </div>
    <!-- End Left menu area -->

templates/partials/_stu_navbar.html
{% load static %}



<header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="col">
              <div class="site-logo">
                <img src=""  href="{% url 'performance:home-view' %}" style="margin-left:-150px;"><strong>SPPS</strong></img>
              </div>
            </div>

            <div class="col-9 text-right text-lg-left">

              <span class="d-inline-block d-lg-none"><a href="#" class=" site-menu-toggle js-menu-toggle py-5 "><span class="icon-menu h3 text-black"></span></a></span>

              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class="active"><a href="{% url 'performance:home-view' %}" class="nav-link" >Home</a></li>






                    <li class="active"><a href="{% url 'performance:login-view' %}" class="nav-link">LogIn</a></li>




                </ul>
              </nav>
            </div>


          </div>
        </div>


      </header>



<style>


   nav ul li a.nav-link:hover{

        color:red;


    }




</style>

templates/partials/_stu_sidebar.html
{% load static%}
<style>
    .this-is-main-logo{
    width:100px;
    height:56px;
    }
.sidebar-header{
    background:#fee2b3;
    height: 13%;

}

</style>
<style>
    # sidebar-view{
    background:#f96359;

    }
</style>
<!-- Start Left menu area -->
    <div class="left-sidebar-pro">
        <nav id="sidebar" class="" >
            <div class="sidebar-header" style="background:#fee2b3;">
                <img src=""  href="{% url 'performance:home-view' %}" style="margin-left:-150px;"><h1 style="color:black;">SPPS</h1></img>
            </div>
            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li>
                            <a  href="{% url 'performance:dashboard-view' %}" aria-expanded="false"><span class="educate-icon educate-home icon-wrap"></span> <span class="mini-click-non">DASHBOARD</span></a>
                        </li>


                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false"><span class="educate-icon educate-checked edu-checked-pro admin-check-pro"></span> <span class="mini-click-non">FILES</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="Projects List" href="{% url 'performance:file-create' %}"><span class="mini-sub-pro">UPLOAD FILES</span></a></li>
                                <li><a title="Projects List" href="{% url 'performance:file-list' %}"><span class="mini-sub-pro">LIST OF FILES</span></a></li>
<!--                                -->



                            </ul>
                        </li>



                    </ul>
                </nav>
            </div>
        </nav>
    </div>
    <!-- End Left menu area -->

templates/partials/after_login_navbar.html
<header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="col">
              <div class="site-logo">
                <a href="index.html"><strong>Notary</strong></a>
              </div>
            </div>

            <div class="col-9 text-right text-lg-left">

              <span class="d-inline-block d-lg-none"><a href="#" class=" site-menu-toggle js-menu-toggle py-5 "><span class="icon-menu h3 text-black"></span></a></span>

              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class="active"><a href="index.html" class="nav-link">Home</a></li>


                  <li><a href="about.html" class="nav-link">About</a></li>


                    <li class="nav-item dropdown nav-user" style="color:green;">

                <a href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false" class="fas fa-user-circle fa-2x "style="margin-top:10px;"></a>
                <div class="dropdown-menu dropdown-menu-right nav-user-dropdown"
                     aria-labelledby="navbarDropdownMenuLink2">
                    <div class="nav-user-info" style="background-color:#003875;">
                        <h5 class="mb-0 text-white nav-user-name">{{request.user}}</h5>
                        <span class="status"></span><span class="ml-2">Available</span>
                    </div>

                    <a class="dropdown-item" href="" style="color:#c33;"><i class="fas fa-power-off mr-2" style="color:#c33;"></i>Logout</a>
                </div>
            </li>


                </ul>
              </nav>
            </div>


          </div>
        </div>

      </header>

templates/partials/student_navbar.html
{% load static %}
<div class="all-content-wrapper">
    <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="logo-pro" style="margin-top: 40px;" >
                    </div>
                </div>
            </div>
        </div>
    <div class="header-advance-area">
        <div class="header-top-area" style="background:#fee2b3; height:13%;" >
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="header-top-wraper">
                                <div class="row">
                                    <div class="col-lg-1 col-md-0 col-sm-1 col-xs-12">

                                    </div>
                                    <div class="col-lg-6 col-md-7 col-sm-6 col-xs-12">
                                    </div>
                                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                        <div class="header-right-info">
                                            <ul class="nav navbar-nav mai-top-nav header-right-menu">
                                                        <li class="nav-item">


                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class="active"><a href="{% url 'performance:home-view' %}" class="nav-link" style="color:black;">Home</a></li>







<!--                     <li class="nav-item dropdown nav-user" style="color:#00FF00;">-->

                <a href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false" class="fas fa-user-circle fa-2x "style="margin-top:10px;color:#00FF00;"></a>
                <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                    <div class="nav-user-info">
                        <h5 class="mb-0 text-white nav-user-name" style="color:#00FF00">{{request.user}}</h5>
                        <span class="status"></span><span class="ml-2">Available</span>
                    </div>

                    <a class="dropdown-item" href="" style="color:#c33;"><i class="fas fa-power-off mr-2" style="color:#c33;"></i>Logout</a>
                </div>
            </li>





<!--                                                            <a href="#" data-toggle="" role="button" aria-expanded="false" class="nav-link">-->
<!--                                                                    <span class="admin-name">Welcome {{request.user}}</span>-->

<!--                                                                </a>-->
<!--                                                             <a href="{% url 'performance:logout' %}" data-toggle="" role="button" aria-expanded="false" class="nav-link">-->
<!--                                                                    <span class="admin-name">Logout</span>-->

<!--                                                                </a>-->

                                                        </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>







<style>

ul {
    list-style: outside none none;
}
.text-right {
    text-align: right !important;
}
.text-right {
    text-align: right;
}
.text-lg-left {
    text-align: left !important;
}
body {
    line-height: 1.7;
    color: #364d59 !important;
    font-weight: 300;
    font-size: 1rem;

}


.nav-link {
    margin-right: 20px;
    margin-left: 20px;
}


 </style>