Student_Performance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
   path('',include('performance.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

performance/urls.py
from django.urls import path

from .views import FileCreateView,FileDetailView,FileDeleteView,FileListView, LoginView,DashboardView, signout , SearchView, Home





app_name = 'performance'
urlpatterns = [

    path('', Home.as_view(), name='home-view'),
    path('login/', LoginView.as_view(), name='login-view'),
    path('dashboard/', DashboardView.as_view(), name='dashboard-view'),

    path('logout/',signout,name='logout'),


    path('file-create/',FileCreateView.as_view(),name='file-create'),
    path('file-list/',FileListView.as_view(),name='file-list'),
    path('file-detail/<int:pk>/',FileDetailView.as_view(),name='file-detail'),
    #path('detail/file-update/<int:pk>/',FileUpdate.as_view(),name='file-update'),
    path('file-delete/<int:pk>/',FileDeleteView.as_view(),name='file-delete'),

    path('search/<int:pk>',SearchView.as_view(),name='file-search'),

]

templates/files/file-create.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}


<div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
</div>
<div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-payment-inner-st">
                            <ul id="myTabedu1" class="tab-review-design">
                                <li class="active"><a href="#description">Add File</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                             <div class="review-content-section">
                                                <form id="add-department" action="{% url 'performance:file-create' %} " class="add-department" method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                            <div class="form-group" style="width:138%;">
                                                                <label for="name">Name</label>
                                                                {{form.name}}
                                                            </div>
                                                            <div class="form-group" style="width:138%;">
                                                                <label for="File">File</label>
                                                                {{form.file}}
                                                            </div>

                                                            <div class="form-group">
                                                                <label for="File">Description</label>
                                                                {{form.description}}
                                                                {{form.media}}
                                                            </div>

                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="payment-adress">
                                                                <button type="submit" class="btn btn-primary waves-effect waves-light" style="align:right;">Add File</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/files/file-delete.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}


<div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
</div>
<div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-payment-inner-st">
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                             <div class="review-content-section">
                                                <form id="add-department" action="" class="add-department" method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="row">
                                                        <ul id="myTabedu1" class="tab-review-design">
                                                            <li class="active"><a href="">Delete File?</a></li>
                                                        </ul>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="payment-adress">
                                                                <button type="submit" class="btn btn-primary waves-effect waves-light" name="delete">Delete </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/files/file-detail.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}




<br>
<br>



<table class="table table-bordered" id="datatable" width="100%" cellspacing="0">

    <thead>
    <tr>
        {% for col in columns %}
        <th>{{ col }}</th>
        {% endfor %}

    </tr>
    </thead>
    <tbody>
    {% for  val in rows %}


    <tr>
        <td>
            {{val.symbol}}
        </td>

        <td>
            {{val.semester}}

        </td>

        <td>
            {{val.total_internal}}
        </td>

        <td>
            {{val.total_external}}
        </td>

        <td>
            {{val.total_marks}}
        </td>
        <td>
            {{val.subject}}
        </td>
        <td>
            {{val.percentage}}
        </td>


    </tr>

    {% endfor %}
    </tbody>
</table>


{% endblock %}

templates/files/file-list.html
{% extends 'base1.html' %}
{% block content %}
{% load static %}





        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row" style="margin-top:100px;">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap drp-lst">
                            <h4>File List</h4>
                            <div class="add-product">
                                <a href="{% url 'performance:file-create' %}">Add File</a>
                            </div>


                            <div class="asset-inner">
                                <table  data-toggle="table" data-pagination="true" data-search="true"  >
                                    <thead>
                                        <th>Name</th>

                                        <th>Size</th>

                                        <th>Operations</th>
                                    </thead>


                                   <tbody>





                                   {% for i in file %}




                                    <tr>
                                        <td><a class="button is-info" href="{%url 'performance:file-detail' i.id%}">{{ i.name }}&nbsp;</a></td>

                                         <td>{{i.file.size|filesizeformat}}</td>


                                        <td>

                                            <button data-toggle="tooltip"  class="pd-setting-ed"><i  class="fa fa-pencil-square-o" aria-hidden="true">&nbsp;<a  href="{% url 'performance:file-detail' i.id %}">View</a></i></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true">&nbsp;<a  href="{% url 'performance:file-delete' i.id %}">Delete</a></i></button>



                                            <form id="add-department" action=""  class="add-department" method="post">

                                         {% csrf_token %}

                                                <button type="submit" value="{{i.id}}" name="list" class="btn btn-primary waves-effect waves-light" style="align:right;"><a  href="{% url 'performance:file-search' i.id %}">Search</a></button>




                                                </form>





                                        </td>







                                    </tr>

                                   {% endfor %}
                                   </tbody>


                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}